### ISSUE TITLE
pre commit hook failed with error

### ISSUE THREAD

**Issue by wjm2202** [mitchell985/Node-Project#1]
hi mitchel there is a problem with the jest test pre commit hook 
![mitchel precommit failed](https://user-images.githubusercontent.com/16139807/180586745-8c3ab099-37f9-411e-9ba7-b11c3f90afb5.png)
i think you need to clone in new location and switch to dev branch.
make a change nd try to commit.

Glen

**Comment by mitchell985** [comment]
According to this article. https://stackoverflow.com/questions/60976511/globalthis-underfined-for-jest-test-cases
Try updating node to version 16.

If you have any issues check this out.
https://github.com/nodesource/distributions/issues/1157

Then run `yarn install` to check everything is update to date again.
